community-tooling/charts

renovate.json
This migrates the renovate config to the one for version 36.0.0 and later.
=> chore: migrate to renovate 36 template name

renovate.json
This ignores commits from pre-commit.ci on renovate PRs, unblocking them.
=> chore: ignore pre-commit.ci commits

.github/workflows/update-hcloud-cloud-controller-manager.yml, .github/workflows/update-hcloud-csi-driver.yml, .github/workflows/update-kube-prometheus-stack-crds.yml
This is needed to so that the chart updates trigger other workflows.
=> ci: use bot token to update charts

renovate.json
Strips the "v" prefix since it is not part of the needed version.
=> fix: strip v prefix from external-dns

ct.yaml
The release secret is too large now. helm does not support SSA yet.
Deactivating the test until it does.
=> test: exclude kps-crds

charts/mailtrain/Chart.yaml, charts/mailtrain/README.md, charts/mailtrain/README.md.gotmpl
This chart is for mailtrain v1, which is EOL for a while.
=> chore: deprecate mailtrain chart

charts/cronjob/Chart.yaml, charts/cronjob/README.md, charts/cronjob/ci/configmap-map-values.yaml, charts/cronjob/ci/configmap-string-values.yaml, charts/cronjob/templates/configmap.yaml
This adds the possibility to use non-string values for ConfigMap keys.
=> feat(cronjob): allow maps as ConfigMap values

charts/generic/Chart.yaml, charts/generic/README.md, charts/generic/ci/configMap-values.yaml, charts/generic/templates/deployment.yaml
This fixes a typo in the `if` surrounding the `volumes` block that prevents
the whole block from getting created if `.Values.configMap` does only use the
`data` and `mountFiles` parameters.
=> fix: configure volume when only configMap.mountFiles is set

.github/workflows/renovate-config-validator-skip.yml, .github/workflows/renovate-config-validator.yml, .pre-commit-config.yaml, renovate.json
Reverts community-tooling/charts#117
The renovate config is invalid and the check doesn't seem to catch it because we don't run pre-commit in the CI yet. Reverting for now, so renovate works while we work on a fix.
=> ci: Revert "ci: more automerging"

renovate.json
- Enables renovate automerging for everything but major upgrades
- Major upgrades for some dependencies are automerged as per `packageRule`
- Updates the `regexManagers` key to `customManagers`
- Removes unneeded `platformAutomerge`
=> ci: next try for renovate automerging

charts/generic/Chart.yaml, charts/generic/README.md, charts/generic/ci/topologySpreadConstraints-values.yaml, charts/generic/templates/deployment.yaml, charts/generic/values.yaml
This adds the ability to set `topologySpreadConstraints`.
See https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/ for documentation.
=> feat: add topologySpreadConstraints

charts/generic/Chart.yaml, charts/generic/README.md, charts/generic/templates/_helpers.tpl, charts/generic/templates/deployment.yaml
This fixes a bug where the pod did not have all labels applied, leading to affinities not being applied.
=> fix: pod now has all labels

charts/cronjob/Chart.yaml, charts/cronjob/README.md, charts/cronjob/ci/suspend-values.yaml, charts/cronjob/templates/cronjob.yaml, charts/cronjob/values.yaml
This enables suspension to be configured for the `cronjob` chart.
=> feat: enable suspend configuration for CronJob

charts/cronjob/Chart.yaml, charts/cronjob/README.md, charts/cronjob/ci/default-values.yaml, charts/cronjob/templates/cronjob.yaml, charts/cronjob/values.yaml
With this, the `.spec.concurrencyPolicy` of a CronJob can be specified.
=> feat: enable specification of ConcurrencyPolicy

charts/cronjob/Chart.yaml, charts/cronjob/README.md, charts/cronjob/templates/pvc.yaml, charts/cronjob/values.yaml
This allows to specify an existing PerstistentVolume to be used for the CronJob's PVC
=> feat: enable specification of existing volume for CronJob

charts/generic/Chart.yaml, charts/generic/README.md, charts/generic/ci/default-values.yaml, charts/generic/ci/semver-values.yaml, charts/generic/templates/_helpers.tpl
This fixes an issue where the app.kubernetes.io/version label contains invalid characters
if a sha256 hash is used.
These are specified as latest@sha256:6703475278611b5a8871769095cb1b5c624ab4d2d9d3874d81afdbe1cb4b8cce, but
@ and : are forbidden characters in labels, and the maximum value length is 63.
Therefore, we now extract only valid characters at the end of the tag for the app.kubernetes.io/version label.
This is fully compatible with existing versions and yields:
* The SHA256 hash for SHA256 tags
* The exact tag for semver tags
* Whatever is left over when looking for only alphanumeric characters and -_. from the end of the tag
Resolves #246.
=> fix: app.kubernetes.io/version label invalid for sha256 tags

charts/generic/Chart.yaml, charts/generic/README.md, charts/generic/ci/floating-point-values.yaml, charts/generic/templates/_helpers.tpl
This quotes the version tag so that `{number}.{number}` tags are not interpreted as floating point numbers, but strings.
Resolves #279.
=> fix: quote version tag for {number}.{number} tags

.github/workflows/lint-and-test.yml, charts/cronjob/Chart.yaml, charts/cronjob/README.md, charts/cronjob/README.md.gotmpl, charts/cronjob/ci/default-values.yaml, charts/cronjob/templates/cronjob.yaml, charts/cronjob/values.yaml, ci/install-crds.sh, ci/setup.sh
This adds `envFrom` configurability to the cronjob chart.
=> feat: add envFrom to cronjob chart

.github/workflows/pre-commit.yml
With this, changes made by pre-commit will be commited and pushed (again). This was done by pre-commit.ci before, but since that does not support helm unittest, we had to move back to in-workflow pre-commit.
=> fix: commit changes from pre-commit

charts/cronjob/Chart.yaml, charts/cronjob/README.md, charts/cronjob/ci/configmap-string-values.yaml, charts/cronjob/templates/cronjob.yaml, charts/cronjob/values.yaml
To deploy e.g. scripts, you need to set the defaultMode. This PR enables that.
=> feat: add support for defaultMode specification

.github/workflows/pre-commit.yml
This updates the pre-commit workflow to only push back fixes when the PR originates in the repo itself.
With this, the workflow also works for PRs from forks, not only PRs from the repo itself.
=> fix: pre-commit for forks

charts/generic/Chart.yaml, charts/generic/README.md, charts/generic/UPGRADING.md, charts/generic/templates/_helpers.tpl, charts/generic/templates/deployment.yaml, charts/generic/tests/securitycontext_test.yaml, charts/generic/values.yaml
Ref: https://anaconda.atlassian.net/browse/CORE-7479
This PR lets users of the `generic` chart set `podSecurityStandard: restricted` to automatically set defaults for `podSecurityContext` and `securityContext` which are compliant with the "restricted" [Pod Security Standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/).
Users can override these defaults (to either increase or decrease security) by setting `securityContext` or `podSecurityContext` (the dicts are merged together).
Also added the `automountServiceAccountToken` value. It defaults to false when not creating a serviceaccount, which is a CIS recommendation to avoid mounting an unnecessary default serviceaccount token which may accidentally have permissions assigned to it.
For example, a fully hardened …
=> feat: Add podSecurityStandard setting to make hardening easy

renovate.json
With this change, the bot user maintained my @morremeyer is ignored for renovate PR updates.
=> ci: ignore commits by pre-commit bot user for renovate

charts/cronjob/Chart.yaml, charts/cronjob/README.md, charts/cronjob/templates/cronjob.yaml, charts/cronjob/tests/history_test.yaml, charts/cronjob/values.yaml
I want to set `successfulJobsHistoryLimit` and/or `failedJobsHistoryLimit` to zero but the current chart wouldn't let me.
This PR fixes that and also adds tests.
=> fix: allow job history limits to be set to zero in cronjob chart

charts/cronjob/Chart.yaml, charts/cronjob/README.md, charts/cronjob/templates/cronjob.yaml, charts/cronjob/values.yaml
- Adds the `backoffLimit` option to the cronjob template
- Defaults to `6`, which is the default set by Kubernetes
This is my first time working on this project. As far as I could tell, this all the wiring that is needed, but please let me know if I missed something.
=> feat: Adds `backoffLimit` to cronjob template

charts/generic/Chart.yaml, charts/generic/README.md, charts/generic/ci/configMap-disabled-values.yaml, charts/generic/templates/deployment.yaml
Fixes a bug where disabling the ConfigMap did indeed remove the ConfigMap, but not it being mounted in the Deployment.
=> fix: disable mounting of ConfigMap when it is disabled
